POST http://localhost:7071/api/AddReview HTTP/1.1
content-type: application/json

{
    "userid": "1",
    "title": "Gone with the wind",
    "author": "Margaret Mitchell",
    "review": "A great book!",
    "rating": 5
}